# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "matteodroids"
license = "GPLv3"
licenselink = "https://www.gnu.org/licenses/gpl-3.0.en.html"
description = "Theme for matteodroids.science"
homepage = "https://matteodroids.science"
tags = ["website", "responsive", "academic", "CV"]
features = []
min_version = "0.41.0"

[author]
    name = "Matteo De Carlo"
    homepage = "matteodroids.science"
